#!/bin/bash

# Script to open database terminals for Auth DB and Core Banking DB
# Run this script and it will provide commands for two terminals

echo "=========================================="
echo "Database Terminal Commands"
echo "=========================================="
echo ""
echo "TERMINAL 1 - Auth Database (Primary):"
echo "----------------------------------------"
echo "docker exec -it db-auth-primary psql -U postgres_user -d auth_db"
echo ""
echo "TERMINAL 2 - Core Banking Database (Primary):"
echo "----------------------------------------"
echo "docker exec -it db-core-banking-primary psql -U postgres_user -d core_banking_db"
echo ""
echo "=========================================="
echo "Useful SQL Commands for Monitoring:"
echo "=========================================="
echo ""
echo "=== AUTH DATABASE (Terminal 1) ==="
echo ""
echo "-- Watch users being registered:"
echo "SELECT user_id, username, email, phone_number, created_at FROM users ORDER BY created_at DESC LIMIT 10;"
echo ""
echo "-- Watch payment methods:"
echo "SELECT payment_method_id, user_id, provider, card_type, last_4, created_at FROM payment_methods ORDER BY created_at DESC LIMIT 10;"
echo ""
echo "-- Watch subscriptions:"
echo "SELECT subscription_id, user_id, amount, currency, frequency, status, next_payment_date FROM subscriptions ORDER BY created_at DESC LIMIT 10;"
echo ""
echo "-- Monitor live activity:"
echo "SELECT COUNT(*) as total_users, MAX(created_at) as latest_user FROM users; \\watch 2"
echo ""
echo "=== CORE BANKING DATABASE (Terminal 2) ==="
echo ""
echo "-- Watch accounts being created:"
echo "SELECT account_id, user_id, account_type, currency, status, created_at FROM accounts ORDER BY created_at DESC LIMIT 10;"
echo ""
echo "-- Watch account balances:"
echo "SELECT ab.account_id, a.user_id, ab.balance, ab.version, ab.updated_at FROM account_balances ab JOIN accounts a ON ab.account_id = a.account_id ORDER BY ab.updated_at DESC LIMIT 10;"
echo ""
echo "-- Watch transactions:"
echo "SELECT transaction_id, transaction_type, amount, currency, status, from_account_id, to_account_id, created_at FROM transactions ORDER BY created_at DESC LIMIT 10;"
echo ""
echo "-- Monitor live activity:"
echo "SELECT COUNT(*) as total_accounts, MAX(created_at) as latest_account FROM accounts; \\watch 2"
echo ""
echo "=========================================="
echo "Quick Start:"
echo "=========================================="
echo "1. Open Terminal 1 and run:"
echo "   docker exec -it db-auth-primary psql -U postgres_user -d auth_db"
echo "   Then: SELECT COUNT(*) as total_users FROM users; \\watch 2"
echo ""
echo "2. Open Terminal 2 and run:"
echo "   docker exec -it db-core-banking-primary psql -U postgres_user -d core_banking_db"
echo "   Then: SELECT COUNT(*) as total_accounts FROM accounts; \\watch 2"
echo ""
echo "3. In a third terminal, run the demo:"
echo "   cd /home/ubuntu/samri/Payment-Orchestration-Platform"
echo "   node demo/demo-script.js"
echo ""
