#!/bin/bash

# Script to open database terminals for monitoring
# Run this script and it will provide commands for two terminals

echo "=========================================="
echo "Database Terminal Commands"
echo "=========================================="
echo ""
echo "TERMINAL 1 - Primary Database (Writes):"
echo "----------------------------------------"
echo "docker exec -it db-core-banking-primary psql -U postgres_user -d core_banking_db"
echo ""
echo "TERMINAL 2 - Replica Database (Reads):"
echo "----------------------------------------"
echo "docker exec -it db-core-banking-replica psql -U postgres_user -d core_banking_db"
echo ""
echo "=========================================="
echo "Useful SQL Commands for Monitoring:"
echo "=========================================="
echo ""
echo "-- Watch accounts being created (run in PRIMARY):"
echo "SELECT account_id, user_id, account_type, currency, status, created_at FROM accounts ORDER BY created_at DESC LIMIT 10;"
echo ""
echo "-- Watch account balances (run in PRIMARY):"
echo "SELECT ab.account_id, a.user_id, ab.balance, ab.version, ab.updated_at FROM account_balances ab JOIN accounts a ON ab.account_id = a.account_id ORDER BY ab.updated_at DESC LIMIT 10;"
echo ""
echo "-- Watch transactions (run in PRIMARY):"
echo "SELECT transaction_id, transaction_type, amount, currency, status, from_account_id, to_account_id, created_at FROM transactions ORDER BY created_at DESC LIMIT 10;"
echo ""
echo "-- Check replication status (run in REPLICA):"
echo "SELECT pg_is_in_recovery();"
echo ""
echo "-- Monitor live activity (in psql, after running a SELECT query):"
echo "\\watch 2  (runs the previous query every 2 seconds)"
echo ""
echo "-- Example: Watch accounts update in real-time:"
echo "SELECT COUNT(*) as total_accounts, MAX(created_at) as latest_account FROM accounts; \\watch 2"
echo ""
